declare const FIREBASE_API_KEY: any;
declare const FIREBASE_AUTH_DOMAIN: any;
declare const FIREBASE_DATABASE_URL: any;
declare const FIREBASE_PROJECT_ID: any;
declare const FIREBASE_STORAGE_BUCKET: any;
declare const FIREBASE_MESSAGING_SENDER_ID: any;
declare const FIREBASE_APP_ID: any;
declare const FIREBASE_MEASUREMENT_ID: any;
export { FIREBASE_API_KEY, FIREBASE_AUTH_DOMAIN, FIREBASE_DATABASE_URL, FIREBASE_PROJECT_ID, FIREBASE_STORAGE_BUCKET, FIREBASE_MESSAGING_SENDER_ID, FIREBASE_APP_ID, FIREBASE_MEASUREMENT_ID, };
