const ENV_PATH = import.meta.env;

const FIREBASE_API_KEY = ENV_PATH.VITE_FIREBASE_API_KEY;
const FIREBASE_AUTH_DOMAIN = ENV_PATH.VITE_FIREBASE_AUTH_DOMAIN;
const FIREBASE_DATABASE_URL = ENV_PATH.VITE_FIREBASE_DATABASE_URL;
const FIREBASE_PROJECT_ID = ENV_PATH.VITE_FIREBASE_PROJECT_ID;
const FIREBASE_STORAGE_BUCKET = ENV_PATH.VITE_FIREBASE_STORAGE_BUCKET;
const FIREBASE_MESSAGING_SENDER_ID = ENV_PATH.VITE_FIREBASE_MESSAGING_SENDER_ID;
const FIREBASE_APP_ID = ENV_PATH.VITE_FIREBASE_APP_ID;
const FIREBASE_MEASUREMENT_ID = ENV_PATH.VITE_FIREBASE_MEASUREMENT_ID;

export {
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_DATABASE_URL,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID,
};
